{
 "title": "Cloudflared Tunnel",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Cloudflare", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Locations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cloudflared_tunnel_server_locations{job=\"cloudflared\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_ha_connections{job=\"cloudflared\"}"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_request_errors{job=\"cloudflared\"}"
    }
   ]
  },
  {
   "title": "Requests Proxied",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_total_requests{job=\"cloudflared\"}"
    }
   ]
  },
  {
   "title": "Timer Retries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_timer_retries{job=\"cloudflared\"}"
    }
   ]
  },
  {
   "title": "Concurrent Requests per Tunnel",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_concurrent_requests_per_tunnel{job=\"cloudflared\"}"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(cloudflared_tunnel_response_by_code{job=\"cloudflared\"}[5m])",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  { "title": "Cloudflare Legacy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Server Locations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cloudflared_tunnel_server_locations{job=\"cloudflared_legacy\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_ha_connections{job=\"cloudflared_legacy\"}"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_request_errors{job=\"cloudflared_legacy\"}"
    }
   ]
  },
  {
   "title": "Requests Proxied",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_total_requests{job=\"cloudflared_legacy\"}"
    }
   ]
  },
  {
   "title": "Timer Retries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_timer_retries{job=\"cloudflared_legacy\"}"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_active_streams{job=\"cloudflared_legacy\"}"
    }
   ]
  },
  {
   "title": "Concurrent Requests per Tunnel",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_concurrent_requests_per_tunnel{job=\"cloudflared_legacy\"}"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(cloudflared_tunnel_response_by_code{job=\"cloudflared_legacy\"}[5m])",
     "legendFormat": "{{status_code}}"
    }
   ]
  }
 ]
}