{
 "title": "Monitors",
 "tags": [ "alerts" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Basic - Server",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"192.168.1.22:9100\",mode=\"system\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_System",
     "stepMode": "min"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.22:9100\",mode=\"user\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_User",
     "stepMode": "min"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.22:9100\",mode=\"iowait\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Iowait",
     "stepMode": "min"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.22:9100\",mode=\"idle\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Total",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "CPU Basic - Azero",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"192.168.1.2:9100\",mode=\"system\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_System",
     "stepMode": "min"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.2:9100\",mode=\"user\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_User",
     "stepMode": "min"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.2:9100\",mode=\"iowait\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Iowait",
     "stepMode": "min"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.2:9100\",mode=\"idle\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Total",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "CPU Basic - Nuc",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"192.168.1.23:9100\",mode=\"system\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_System",
     "stepMode": "min"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.23:9100\",mode=\"user\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_User",
     "stepMode": "min"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.23:9100\",mode=\"iowait\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Iowait",
     "stepMode": "min"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.23:9100\",mode=\"idle\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Total",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "CPU Basic - HP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"192.168.1.193:9100\",mode=\"system\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_System",
     "stepMode": "min"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.193:9100\",mode=\"user\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_User",
     "stepMode": "min"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.193:9100\",mode=\"iowait\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Iowait",
     "stepMode": "min"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.193:9100\",mode=\"idle\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Total",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Memory Basic - Server",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"server\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"server\"} - node_memory_MemFree_bytes{node=~\"server\"} - (node_memory_Cached_bytes{node=~\"server\"} + node_memory_Buffers_bytes{node=~\"server\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{node=~\"server\"}",
     "legendFormat": "RAM Free"
    }
   ]
  },
  {
   "title": "Memory Basic - Azero",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"azero\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"azero\"} - node_memory_MemFree_bytes{node=~\"azero\"} - (node_memory_Cached_bytes{node=~\"azero\"} + node_memory_Buffers_bytes{node=~\"azero\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{node=~\"azero\"}",
     "legendFormat": "RAM Free"
    }
   ]
  },
  {
   "title": "Memory Basic - Nuc",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"nuc\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"nuc\"} - node_memory_MemFree_bytes{node=~\"nuc\"} - (node_memory_Cached_bytes{node=~\"nuc\"} + node_memory_Buffers_bytes{node=~\"nuc\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{node=~\"nuc\"}",
     "legendFormat": "RAM Free"
    }
   ]
  },
  {
   "title": "Memory Basic - HP",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"hp\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"hp\"} - node_memory_MemFree_bytes{node=~\"hp\"} - (node_memory_Cached_bytes{node=~\"hp\"} + node_memory_Buffers_bytes{node=~\"hp\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{node=~\"hp\"}",
     "legendFormat": "RAM Free"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic - Server",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'192.168.1.22:9100',fstype=~\"ext4|xfs|fuseblk\"} / node_filesystem_size_bytes{instance=~'192.168.1.22:9100',fstype=~\"ext4|xfs|fuseblk\"})",
     "legendFormat": "{{instance}}：{{mountpoint}}",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic - Azero",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'192.168.1.2:9100',fstype=~\"ext4|xfs|fuseblk\"} / node_filesystem_size_bytes{instance=~'192.168.1.2:9100',fstype=~\"ext4|xfs|fuseblk\"})",
     "legendFormat": "{{instance}}：{{mountpoint}}",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic - Nuc",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'192.168.1.23:9100',fstype=~\"ext4|xfs|fuseblk\"} / node_filesystem_size_bytes{instance=~'192.168.1.23:9100',fstype=~\"ext4|xfs|fuseblk\"})",
     "legendFormat": "{{instance}}：{{mountpoint}}",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic - Nuc",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'192.168.1.193:9100',fstype=~\"ext4|xfs|fuseblk\"} / node_filesystem_size_bytes{instance=~'192.168.1.193:9100',fstype=~\"ext4|xfs|fuseblk\"})",
     "legendFormat": "{{instance}}：{{mountpoint}}",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Network RX/TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{node=\"server\"}[$__interval]))",
     "legendFormat": "TX"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{node=\"server\"}[$__rate_interval]))",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Network RX/TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{node=\"azero\"}[$__interval]))",
     "legendFormat": "TX"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{node=\"azero\"}[$__rate_interval]))",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Network RX/TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{node=\"nuc\"}[$__interval]))",
     "legendFormat": "TX"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{node=\"nuc\"}[$__rate_interval]))",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Network RX/TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{node=\"hp\"}[$__interval]))",
     "legendFormat": "TX"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{node=\"hp\"}[$__rate_interval]))",
     "legendFormat": "RX"
    }
   ]
  }
 ]
}