{
 "title": "Monitors",
 "tags": [ "alerts" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Basic - Pi",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"192.168.1.13:9100\",mode=\"system\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_System",
     "stepMode": "min"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.13:9100\",mode=\"user\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_User",
     "stepMode": "min"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.13:9100\",mode=\"iowait\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Iowait",
     "stepMode": "min"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.13:9100\",mode=\"idle\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Total",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "CPU Basic - Server",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"192.168.1.22:9100\",mode=\"system\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_System",
     "stepMode": "min"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.22:9100\",mode=\"user\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_User",
     "stepMode": "min"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.22:9100\",mode=\"iowait\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Iowait",
     "stepMode": "min"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.22:9100\",mode=\"idle\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Total",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "CPU Basic - Azero",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"192.168.1.2:9100\",mode=\"system\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_System",
     "stepMode": "min"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.2:9100\",mode=\"user\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_User",
     "stepMode": "min"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.2:9100\",mode=\"iowait\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Iowait",
     "stepMode": "min"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"192.168.1.2:9100\",mode=\"idle\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Total",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Memory Basic - Pi",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"pi\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"pi\"} - node_memory_MemFree_bytes{job=~\"pi\"} - (node_memory_Cached_bytes{job=~\"pi\"} + node_memory_Buffers_bytes{job=~\"pi\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=~\"pi\"}",
     "legendFormat": "RAM Free"
    }
   ]
  },
  {
   "title": "Memory Basic - Server",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"server\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"server\"} - node_memory_MemFree_bytes{job=~\"server\"} - (node_memory_Cached_bytes{job=~\"server\"} + node_memory_Buffers_bytes{job=~\"server\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=~\"server\"}",
     "legendFormat": "RAM Free"
    }
   ]
  },
  {
   "title": "Memory Basic - Azero",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"azero\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"azero\"} - node_memory_MemFree_bytes{job=~\"azero\"} - (node_memory_Cached_bytes{job=~\"azero\"} + node_memory_Buffers_bytes{job=~\"azero\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=~\"azero\"}",
     "legendFormat": "RAM Free"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic - Server",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'192.168.1.22:9100',fstype=~\"ext4|xfs|fuseblk\"} / node_filesystem_size_bytes{instance=~'192.168.1.22:9100',fstype=~\"ext4|xfs|fuseblk\"})",
     "legendFormat": "{{instance}}：{{mountpoint}}",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic - Azero",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'192.168.1.2:9100',fstype=~\"ext4|xfs|fuseblk\"} / node_filesystem_size_bytes{instance=~'192.168.1.2:9100',fstype=~\"ext4|xfs|fuseblk\"})",
     "legendFormat": "{{instance}}：{{mountpoint}}",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic - Pi",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'192.168.1.13:9100',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'192.168.1.13:9100',fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{instance}}：{{mountpoint}}",
     "stepMode": "min"
    }
   ]
  },
  {
   "title": "Network RX/TX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{job=\"server\"}[5m])",
     "legendFormat": "Sent - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_packets_total{job=\"server\"}[5m])",
     "legendFormat": "Received - {{device}}"
    }
   ]
  },
  {
   "title": "Network RX/TX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{job=\"azero\"}[5m])",
     "legendFormat": "Sent - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_packets_total{job=\"azero\"}[5m])",
     "legendFormat": "Received - {{device}}"
    }
   ]
  },
  {
   "title": "Network RX/TX",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{job=\"pi\"}[5m])",
     "legendFormat": "Sent - {{device}}"
    },
    {
     "expr": "irate(node_network_receive_packets_total{job=\"pi\"}[5m])",
     "legendFormat": "Received - {{device}}"
    }
   ]
  }
 ]
}